version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bond_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bond_dashboard
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  celery_worker:
    build: ./backend
    command: celery -A utils.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bond_dashboard
    depends_on:
      - backend
      - redis
      - db

  celery_beat:
    build: ./backend
    command: celery -A utils.celery_app beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bond_dashboard
    depends_on:
      - backend
      - redis
      - db

  frontend:
    build: ./bond-dashboard/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./bond-dashboard/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: 