name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Bond-dashboard directory contents:"
          ls -la bond-dashboard || echo "Bond-dashboard directory not found"
          echo "Frontend directory contents:"
          ls -la bond-dashboard/frontend || echo "Frontend directory not found"
          echo "Package files:"
          ls -la bond-dashboard/frontend/package*.json || echo "Package files not found"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            bond-dashboard/frontend/package-lock.json
            bond-dashboard/frontend/package.json
      
      - name: Install Dependencies
        working-directory: bond-dashboard/frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Installing dependencies..."
          npm ci
      
      - name: Build
        working-directory: bond-dashboard/frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Building application..."
          npm run build
      
      - name: List Build Output
        run: |
          echo "Build directory contents:"
          ls -la bond-dashboard/frontend/build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './bond-dashboard/frontend/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 