name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Debug Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend || echo "Frontend directory not found"
      
      - name: Install Dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            echo "Installing dependencies in frontend directory..."
            npm install
          else
            echo "Frontend directory not found. Checking root directory..."
            ls -la
            echo "Installing dependencies in root directory..."
            npm install
          fi
      
      - name: Build
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            echo "Building in frontend directory..."
            npm run build
          else
            echo "Building in root directory..."
            npm run build
          fi
      
      - name: List Build Output
        run: |
          if [ -d "frontend/build" ]; then
            echo "Frontend build directory contents:"
            ls -la frontend/build
          elif [ -d "build" ]; then
            echo "Root build directory contents:"
            ls -la build
          else
            echo "No build directory found!"
            ls -la
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 